### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by Ldalvik** [coderkearns/dexcom#2]
Are there any sort of rate limits I should be aware of? I'm hosting a local server for an IoT Wi-Fi module (Particle Photon) because it doesnt support HTTPS. If im reinitializing the get accountId/get sessionId functions every minute or so, will I have any issues?

Also, when and where is verifying serial numbers needed?

**Comment by coderkearns** [comment]
Im afraid I'm not sure. I created this because i was unable to find any good API docs from dexcom itself. Honestly, you'll want to check out the gagebenne/pydexcom repo for better answers. I made this in an hour just porting their code directly to JS without any best practices.

If they do have rate limiting and you'd like to implement it, feel free to open a PR!

**Comment by Ldalvik** [comment]
Awesome, thanks for the response. Ill look into it soon.

**Comment by gagebenne** [comment]
Verifying serial numbers isn't really useful -- in fact I'm removing it in the next version of `pydexcom`. It checks if a Dexcom transmitter serial number belongs to your account. As for rate limiting -- the closer you can keep things to 5 minutes, I think the better off you are. The lower our limits, the less they look at us, the longer we can use the API.
